### ISSUE TITLE
Users are not properly obtained

### ISSUE THREAD

**Issue by miguelaeh** [Alfresco/acs-community-deployment#99] opened 2020-01-09 15:26 UTC
Hi,
Using the admin tools, at the `Users` section, alfresco try to obtain the content from the following URL:
```
http://<ip>:<port>/share/proxy/alfresco/api/people-enterprise?startIndex=0&pageSize=20&filter=undefined%20%5Bhint%3AuseCQ%5D&sortBy=null&dir=null
```
It is using an `enterprise` URL that returns a `404`. Using the same URL changing `people-enterprise` by `people` the request works, getting a `200` code.
In the file `components/console/users.js` the following line appears:
```
url: Alfresco.constants.PROXY_URI + (parent.options.showAuthorizationStatus ? "api/people-enterprise" : "api/people"),
```
And the `showAuthorizationStatus` seems to be obtained from the users as follow:
```
showAuthorizationStatus = users.getChildValue('show-authorization-status');
```

Is that expected? In the `Users` section I always get:
```
Error loading items
```
As you can see in the following image:
<img width="1264" alt="Screen Shot 2020-01-09 at 4 22 17 PM" src="https://user-images.githubusercontent.com/36923089/72080011-46407c00-32fc-11ea-8d0c-cebe6282abc2.png">

However, searching the users in the top righ search box and in the groups (to add the user to a group) I can find the users correctly.
I didn't perform any change, just downloaded the `docker-compose.yml` and run `docker-compose up`
Regards.

**Comment by Epurashu** [comment] 2020-01-14 10:54
This issue will be closed as a duplicate of [acs-community-packaging#367](https://github.com/Alfresco/acs-community-packaging/issues/367).

Please follow the discussion on the other issue.

**Closed by Epurashu** 2020-01-14 10:54 UTC
