### ISSUE TITLE
Community version calling enterprise api.

### ISSUE THREAD

**Issue by venkattarigopula** [Alfresco/acs-community-deployment#85] opened 2019-10-15 14:38 UTC
Hello, We were created alfresco community docker images using docker-compose file in this repo.

After logged into Admin Tools > Users i am getting error. Please see the below error in the attachment. API is not available (404) as it is pointed to enterprise edition one.

![Screenshot_20191015_192410](https://user-images.githubusercontent.com/30365377/66841713-bfdbfe80-ef87-11e9-9718-13bc40b0fd44.png)

The version of share docker image is 6.2.0-RC4. Problem was not there upto the share image version 6.1.1

Please let help about how to fix.

**Comment by justemu** [comment] 2019-11-10 12:18
1. I have confirmed to reproduce this bug.
2. I have updated the share version to 6.2.0. This bus is still there.

It seem downgrade share is the only workaround now.

**Comment by justemu** [comment] 2019-11-10 13:01
Update:
I have downgraded the share to version 6.1.1. The bug is still there. - Calling "api/people-enterprise", which doesn't exist, leading to a 404 error.
-
Since the problem was not there in 201901GA. I think it should be the problem of the share module in the  repository image.

**Comment by SvenHamers** [comment] 2019-11-25 08:52
Can confirm version 6.1.1 and 6.2 is not working. Forced to downgrade to 6.0.1. Is there any solution yet ?

**Comment by Epurashu** [comment] 2019-11-27 16:12
This is the same issue as [acs-community-packaging#367](https://github.com/Alfresco/acs-community-packaging/issues/367).

As a workaround please read this [comment](https://github.com/Alfresco/acs-community-packaging/issues/367#issuecomment-559152235).

**Comment by Epurashu** [comment] 2019-12-23 12:46
This issue will be closed as a duplicate of [acs-community-packaging#367](https://github.com/Alfresco/acs-community-packaging/issues/367).

**Closed by Epurashu** 2019-12-23 12:46 UTC
